### ISSUE TITLE
404ファイルスペルミス

### ISSUE THREAD

**Issue by SnO2WMaN** [frainworks/frainworks.github.io#2]
404 Tha's an error!　← That's　では?

**Comment by SnO2WMaN** [comment]
http://frainworks.tk/404.html ここの<h1>タグです

**Comment by SnO2WMaN** [comment]
h1タグの部分

**Comment by tsukune-ch** [comment]
https://github.com/frainworks/frainworks.github.io/blob/master/404.html#L52

**Comment by EbXpJ6bp** [comment]
I need good new design site.
